name: Test

on:
  workflow_dispatch:
    inputs:
      title:
        default: "Docker Usage"
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: rhea-so-lab/blog-content-generate-action@main
        id: blog_content
        with:
          open_ai_api_key: ${{ secrets.OPEN_AI_API_KEY }}
          title: ${{ github.event.inputs.title }}
      - run: |
          cat > test.txt <<EOL
          ${{ steps.blog_content.outputs.body }}
          EOL