name: Test

on:
  workflow_dispatch:
    inputs:
      title:
        default: "Docker Usage"
        required: true
        type: string

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: rhea-so-lab/blog-content-generate-action@main
        id: blog_content
        with:
          open_ai_api_key: ${{ secrets.OPEN_AI_API_KEY }}
          title: ${{ github.event.inputs.title }}
      - uses: DamianReeves/write-file-action@master
        with:
          path: test.txt
          contents: ${{ steps.blog_content.outputs.body }}
      - run: cat test.txt
